version: '2'
services:
  hadoop-master:
    hostname: hadoop-master
    image: 'teradatalabs/cdh5-hive'
    ports:
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'

  presto-master:
    hostname: presto-master
    image: 'teradatalabs/centos6-java8-oracle'
    depends_on:
      - 'hadoop-master'
    command: /docker/volumes/presto/presto-product-tests/conf/docker/files/presto-launcher-wrapper.sh distributed-master run
    volumes:
      - ../../../../:/docker/volumes/presto
    env_file:
      - ../../../target/classes/presto.env

  presto-worker:
    image: 'teradatalabs/centos6-java8-oracle'
    depends_on:
      - 'presto-master'
    command: /docker/volumes/presto/presto-product-tests/conf/docker/files/presto-launcher-wrapper.sh distributed-worker run
    volumes_from:
      - presto-master
    env_file:
      - ../../../target/classes/presto.env

  application-runner:
    hostname: application-runner
    image: 'teradatalabs/centos6-java8-oracle'
    depends_on:
      - 'presto-master'
    volumes_from:
      - presto-master
    env_file:
      - ../../../target/classes/presto.env
