version: '2'
services:
  hadoop-master:
    extends:
      file: ../common/docker-compose.yml
      service: hadoop-master-common

  presto-master:
    extends:
      file: ../common/docker-compose.yml
      service: presto-master-common
    command: /docker/volumes/presto/presto-product-tests/conf/docker/files/presto-launcher-wrapper.sh multinode-master run
    depends_on:
       - hadoop-master

  presto-worker:
    extends:
      file: ../common/docker-compose.yml
      service: presto-worker-common
    depends_on:
      - 'presto-master'
    volumes_from:
      - presto-master

  application-runner:
    extends:
      file: ../common/docker-compose.yml
      service: application-runner-common
    depends_on:
      - 'presto-master'
    volumes_from:
      - presto-master

  postgres:
    extends:
      file: ../common/docker-compose.yml
      service: postgres-common

  mysql:
    extends:
      file: ../common/docker-compose.yml
      service: mysql-common
