version: '2'
services:

  java-8-base:
    image: 'teradatalabs/centos6-java8-oracle:jdk1.8.0_92-80a011f'
    env_file:
      - ../../../target/classes/presto.env
    volumes:
      - ../../../../:/docker/volumes/presto

  hadoop-base:
    image: 'teradatalabs/cdh5-hive:2'
    env_file:
      - ../../../target/classes/presto.env
    volumes:
      - ../../../../:/docker/volumes/presto

  hadoop-kerberos:
    # cdh5-hive-kerberized contains keytabs and the `krb5.conf` within
    image: 'teradatalabs/cdh5-hive-kerberized:3'
    env_file:
      - ../../../target/classes/presto.env
    volumes:
      - ../../../../:/docker/volumes/presto

  hadoop-master-common:
    extends:
      service: hadoop-base
    hostname: hadoop-master
    ports:
      - '1080:1080'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'
  
  hadoop-master-kerberos:
    extends:
      service: hadoop-kerberos
    hostname: hadoop-master
    ports:
      - '1080:1080'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'

  presto-master-common:
    extends:
      service: java-8-base
    hostname: presto-master
    volumes:
      - ../../../../presto-product-tests/conf/tempto/tempto-configuration-for-docker-default.yaml:/docker/volumes/tempto/tempto-configuration-local.yaml

  presto-worker-common:
    extends:
      service: java-8-base
    command: /docker/volumes/presto/presto-product-tests/conf/docker/files/presto-launcher-wrapper.sh multinode-worker run

  presto-master-kerberos:
    extends:
      service: hadoop-kerberos
    command: /docker/volumes/presto/presto-product-tests/conf/docker/files/presto-launcher-wrapper.sh singlenode-kerberized run
    volumes:
      - ../../../../presto-product-tests/conf/tempto/tempto-configuration-for-docker-kerberos.yaml:/docker/volumes/tempto/tempto-configuration-local.yaml

  application-runner-common:
    extends:
      service: java-8-base
    hostname: application-runner

  application-runner-kerberos:
    extends:
      service: hadoop-kerberos
    hostname: application-runner

  postgres-common:
    hostname: postgres
    image: 'postgres'
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: swarm
      POSTGRES_USER: swarm
      POSTGRES_DB: test

  mysql-common:
    hostname: mysql
    image: 'mysql'
    ports:
      - '13306:3306'
    environment:
      MYSQL_USER: swarm
      MYSQL_PASSWORD: swarm
      MYSQL_ROOT_PASSWORD: swarm
      MYSQL_DATABASE: test
