databases:
  hive:
    host: hadoop-master
  presto:
    host: presto-master

  alice@presto:
    host: localhost
    server_address: ${databases.presto.host}:8080
    jdbc_driver_class: $[databases.presto.jdbc_driver_class}
    jdbc_url: jdbc:presto://${databases.presto.server_address}/hive/${databases.hive.schema}
    jdbc_user: alice
    jdbc_password: na
    jdbc_pooling: false

  bob@presto:
    host: localhost
    server_address: ${databases.presto.host}:8080
    jdbc_driver_class: $[databases.presto.jdbc_driver_class}
    jdbc_url: jdbc:presto://${databases.presto.server_address}/hive/${databases.hive.schema}
    jdbc_user: bob
    jdbc_password: na
    jdbc_pooling: false
